logging:
  config: classpath:logback.xml

server:
  port: 1719
  servlet:
    context-path: /CEP-API
  error:
    include-stacktrace: never

spring:
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        default_schema: cep

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: cep

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

---

spring:
  config:
    activate:
      on-profile: prod

---

spring:
  config:
    activate:
      on-profile: dev

  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: cep

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: cep